openapi: 3.0.4

# API alapinformációk
info:
  title: FIWARE Smart Transportation API
  version: 1.0.0
  description: |
    REST API a FIWARE smart data modellek alapján, amely közlekedési adatokat szolgáltat.
    Az API NGSI-LD kompatibilis Device, TrafficFlowObserved, RoadSegment, Organization és AnonymousCommuterId entitásokat kezel.
  contact:
    name: API Support
    email: support@example.com

# Szerver konfiguráció
servers:
  - url: https://api.example.com
    description: Production server

# Security sémák - API key alapú autentikáció
security:
  - apiKey: []

components:
  # Security scheme definíció
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: api-key
      description: API kulcs az autentikációhoz. Kérj hozzáférést az adminisztrátoroktól.

  # Sémák - újrafelhasználható objektum definíciók
  schemas:
    # NGSI-LD Property típus - általános property wrapper
    Property:
      type: object
      required:
        - type
        - value
      properties:
        type:
          type: string
          enum: [Property]
          description: NGSI-LD property típus azonosító
        value:
          # A Property value alapértelmezett típusa nincs megadva, ami rugalmasságot biztosít.
          # A konkrét típusokat az allOf részekben adjuk meg.
          description: A property tényleges értéke (lehet string, number, array, stb.)

    # NGSI-LD GeoProperty típus - földrajzi koordináták
    GeoProperty:
      type: object
      required:
        - type
        - value
      properties:
        type:
          type: string
          enum: [GeoProperty]
          description: NGSI-LD geo property típus azonosító
        value:
          type: object
          required:
            - type
            - coordinates
          properties:
            type:
              type: string
              enum: [Point]
              description: GeoJSON geometria típus
            coordinates:
              type: array
              description: Koordináták [longitude, latitude] formátumban (WGS84)
              minItems: 2
              maxItems: 2
              items:
                type: number
              example: [20.1486, 46.2530]

    # NGSI-LD Relationship típus - entitások közötti kapcsolat
    Relationship:
      type: object
      required:
        - type
        - object
      properties:
        type:
          type: string
          enum: [Relationship]
          description: NGSI-LD relationship típus azonosító
        object:
          type: string # Ezt adtam hozzá
          description: Kapcsolódó entitás URN azonosítója vagy üres string
          example: "urn:ngsi-ld:Road:MainRoad01"

    # Device entitás - szenzor eszköz representation
    Device:
      type: object
      required:
        - "@context"
        - id
        - type
      properties:
        "@context":
          type: string
          description: NGSI-LD context URL - sémadefiníciók linkje
          example: "https://smartdatamodels.org/context.jsonld"
        id:
          type: string
          description: Egyedi NGSI-LD azonosító URN formátumban
          pattern: '^urn:ngsi-ld:Device:'
          example: "urn:ngsi-ld:Device:SZG001"
        type:
          type: string
          enum: [Device]
          description: NGSI-LD entitás típus
        deviceCategory:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                value:
                  type: array
                  description: Eszköz kategóriák listája
                  items:
                    type: string
                  example: ["sensor"]
        name:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                value:
                  type: string
                  description: Eszköz beszédes neve (organization név - szenzor név formátumban)
                  example: "Szeged Önkormányzat - Tisza híd szenzor"
        controlledProperty:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                value:
                  type: array
                  description: Eszköz által mért/vezérelt property-k listája
                  items:
                    type: string
                  example: ["trafficFlow"]
        owner:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                value:
                  type: array
                  description: Eszköz tulajdonos(ok) listája
                  items:
                    type: string
                  example: ["urn:ngsi-ld:Organization:szeged-city"] # Példa pontosítása
        location:
          $ref: '#/components/schemas/GeoProperty'

    # AnonymousCommuterId entitás - anonimizált utazó azonosító
    AnonymousCommuterId:
      type: object
      required:
        - "@context"
        - id
        - type
        - anonymizedId
      properties:
        "@context":
          type: string
          description: NGSI-LD context URL - sémadefiníciók linkje
          example: "https://smartdatamodels.org/context.jsonld"
        id:
          type: string
          description: Egyedi NGSI-LD azonosító URN formátumban
          pattern: '^urn:ngsi-ld:AnonymousCommuterId:'
          example: "urn:ngsi-ld:AnonymousCommuterId:TRACK001"
        type:
          type: string
          enum: [AnonymousCommuterId]
          description: NGSI-LD entitás típus
        anonymizedId:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                  value:
                    type: string
                    description: Anonimizált utazó azonosító (track ID)
                    example: "TRACK001"
        orig:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                value:
                  type: string
                  description: Kiindulási irány azonosító
                  example: "Tisza-Lajos út"
        dest:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                value:
                  type: string
                  description: Cél irány azonosító
                  example: "József Attila út"
        location:
          $ref: '#/components/schemas/GeoProperty'

    # RoadSegment entitás - útszakasz representation
    RoadSegment:
      type: object
      required:
        - "@context"
        - id
        - type
      properties:
        "@context":
          description: NGSI-LD context URL vagy URL-ek tömbje
          oneOf:
            - type: string
              example: "https://smartdatamodels.org/context.jsonld"
            - type: array
              items:
                type: string
              example:
                - "https://smartdatamodels.org/context.jsonld"
                - "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
        id:
          type: string
          description: Egyedi NGSI-LD azonosító URN formátumban
          pattern: '^urn:ngsi-ld:RoadSegment:'
          example: "urn:ngsi-ld:RoadSegment:1"
        type:
          type: string
          enum: [RoadSegment]
          description: NGSI-LD entitás típus
        name:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                value:
                  type: string
                  description: Útszakasz neve (irány megnevezés)
                  example: "North Direction"
        description:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                value:
                  type: string
                  description: Útszakasz részletes leírása
                  example: "North Direction"
        refRoad:
          allOf:
            - $ref: '#/components/schemas/Relationship'
            - type: object
              properties:
                object:
                  type: string
                  description: Kapcsolódó út (Road) entitás URN-je
                  pattern: '^urn:ngsi-ld:Road:'
                  example: "urn:ngsi-ld:Road:MainRoad"
        startPoint:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                value: # Ezen belül a GeoJSON definíciója
                  type: object
                  required:
                    - type
                    - coordinates
                  properties:
                    type:
                      type: string
                      enum: [Point]
                      description: GeoJSON geometria típus
                    coordinates:
                      type: array
                      description: Koordináták [longitude, latitude] formátumban (WGS84)
                      minItems: 2
                      maxItems: 2
                      items:
                        type: number
                      example: [0.0, 0.0]
        endPoint:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                value: # Ezen belül a GeoJSON definíciója
                  type: object
                  required:
                    - type
                    - coordinates
                  properties:
                    type:
                      type: string
                      enum: [Point]
                      description: GeoJSON geometria típus
                    coordinates:
                      type: array
                      description: Koordináták [longitude, latitude] formátumban (WGS84)
                      minItems: 2
                      maxItems: 2
                      items:
                        type: number
                      example: [0.0, 0.0]
        allowedVehicleType:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                value:
                  type: array
                  description: Engedélyezett járműtípusok listája
                  items:
                    type: string
                  example: ["anyVehicle"]

    # Organization entitás - szervezet/önkormányzat representation
    Organization:
      type: object
      required:
        - "@context"
        - id
        - type
        - name
      properties:
        "@context":
          type: string
          description: NGSI-LD context URL - sémadefiníciók linkje
          example: "https://smartdatamodels.org/context.jsonld"
        id:
          type: string
          description: Egyedi NGSI-LD azonosító URN formátumban
          pattern: '^urn:ngsi-ld:Organization:'
          example: "urn:ngsi-ld:Organization:municipality-budapest-district5"
        type:
          type: string
          enum: [Organization]
          description: NGSI-LD entitás típus
        name:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                value:
                  type: string
                  description: Szervezet neve
                  example: "Szeged Önkormányzat"

    # Property with observedAt - időbélyeggel rendelkező property
    PropertyWithObservedAt:
      type: object
      required:
        - type
        - value
      properties:
        type:
          type: string
          enum: [Property]
          description: NGSI-LD property típus azonosító
        value:
          type: string # Ezt adtam hozzá (vagy egyéb típus, ha specifikusabb)
          description: A property tényleges értéke
        observedAt:
          type: string
          format: date-time
          description: Megfigyelés időpontja ISO 8601 formátumban
          example: "2025-10-28T10:30:00Z"

    # Property with intensity - mértékegységgel rendelkező property
    PropertyWithIntensity: # Javított név: Intensity
      type: object
      required:
        - type
        - value
      properties:
        type:
          type: string
          enum: [Property]
          description: NGSI-LD property típus azonosító
        value:
          description: A property tényleges értéke (numerikus)
          type: number # Ezt adtam hozzá

    # TrafficFlowObserved entitás - közlekedési forgalom megfigyelés
    TrafficFlowObserved:
      type: object
      required:
        - "@context"
        - id
        - type
      properties:
        "@context":
          type: string
          description: NGSI-LD context URL - sémadefiníciók linkje
          example: "https://smartdatamodels.org/context.jsonld"
        id:
          type: string
          description: Egyedi NGSI-LD azonosító URN formátumban
          pattern: '^urn:ngsi-ld:TrafficFlowObserved:'
          example: "urn:ngsi-ld:TrafficFlowObserved:12345_TRACK001"
        type:
          type: string
          enum: [TrafficFlowObserved]
          description: NGSI-LD entitás típus
        dateObserved:
          allOf:
            - $ref: '#/components/schemas/PropertyWithObservedAt'
            - type: object
              properties:
                value:
                  type: string
                  description: Megfigyelési időintervallum (timeFrom/timeTo formátumban)
                  example: "2025-10-28T10:00:00Z/2025-10-28T10:15:00Z"
                observedAt:
                  type: string
                  format: date-time
                  description: Megfigyelés kezdési időpontja
                  example: "2025-10-28T10:00:00Z"
        intensity:
          allOf:
            - $ref: '#/components/schemas/PropertyWithIntensity' # Javított hivatkozás
            - type: object
              properties:
                value:
                  type: number
                  description: Forgalmi intenzitás értéke (járművek száma)
                  example: 45
        seeAlso:
          allOf:
            - $ref: '#/components/schemas/Relationship'
            - type: object
              properties:
                object:
                  type: string
                  description: Kapcsolódó AnonymousCommuterId entitás URN-je
                  pattern: '^urn:ngsi-ld:AnonymousCommuterId:'
                  example: "urn:ngsi-ld:AnonymousCommuterId:TRACK001"
        vehicleType:
          allOf:
            - $ref: '#/components/schemas/Property'
            - type: object
              properties:
                value:
                  type: string
                  description: Járműtípus azonosító (ObjectLabelId)
                  example: "car"
        refDevice:
          allOf:
            - $ref: '#/components/schemas/Relationship'
            - type: object
              properties:
                object:
                  type: string
                  description: Kapcsolódó Device entitás URN-je (szenzor)
                  pattern: '^urn:ngsi-ld:Device:'
                  example: "urn:ngsi-ld:Device:SZG001"

    # Error response - általános hibaobjektum
    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Hiba rövid típusa
          example: "Unauthorized"
        message:
          type: string
          description: Részletes hibaüzenet
          example: "Invalid or missing API key"
        timestamp:
          type: string
          format: date-time
          description: Hiba időpontja ISO 8601 formátumban
          example: "2025-10-28T10:30:00Z"

# API Endpointok
paths:
  # Endpoint 0: Szervezetek (Organizations) lekérdezése
  /api/v1/organizations:
    get:
      summary: Szervezetek lekérdezése
      description: |
        Visszaadja az összes szervezetet (Organization) tömb formátumban.
        A válasz FIWARE Organization smart data modell szerint strukturált, NGSI-LD kompatibilis formátumban.
        A szervezetek (pl. önkormányzatok) a Device entitásokhoz tartozó organization-eket reprezentálják.
      operationId: getOrganizations
      tags:
        - Organizations

      # Security követelmény
      security:
        - apiKey: []

      # Válaszok
      responses:
        '200':
          description: |
            Sikeres lekérdezés - visszaadja az összes szervezetet array formátumban.
            Minden szervezet tartalmazza a saját @context-jét, azonosítót, típust és nevet.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
              # Példa válasz - Magyar önkormányzatok
              example:
                - "@context": "https://smartdatamodels.org/context.jsonld"
                  id: "urn:ngsi-ld:Organization:municipality-szeged"
                  type: "Organization"
                  name:
                    type: "Property"
                    value: "Szeged Önkormányzat"
                - "@context": "https://smartdatamodels.org/context.jsonld"
                  id: "urn:ngsi-ld:Organization:municipality-budapest-district5"
                  type: "Organization"
                  name:
                    type: "Property"
                    value: "Budapest V. kerület Önkormányzat"
                - "@context": "https://smartdatamodels.org/context.jsonld"
                  id: "urn:ngsi-ld:Organization:municipality-debrecen"
                  type: "Organization"
                  name:
                    type: "Property"
                    value: "Debrecen Önkormányzat"

        '401':
          description: |
            Unauthorized - hiányzó vagy érvénytelen API kulcs.
            Ellenőrizd, hogy az 'api-key' header megfelelően van-e küldve